version: "3.6"

services:
  postgres:
    image: postgres:11.4-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: createvid
      POSTGRES_USER: createvid

  rabbit:
    hostname: rabbit
    ports:
      - 5672:5672
      - 15672:15672
    image: rabbitmq:3.7.17-management-alpine

  api:
    build: ./apps/api.Dockerfile
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://createvid:example@postgres:5432/createvid
      APP_ENDPOINT: http://localhost:8080/
      QUEUE_URL: amqp://rabbit:5672/
    ports:
      - 8080:8080
    volumes:
      - createvid-certs:/keys

  frontend:
    build: ./apps/frontend.Dockerfile
    environment:
      NODE_ENV: development
      API_ENDPOINT: https://localhost:8080/v1/

  marketing:
    build: ./apps/marketing.Dockerfile
    environment:
      NODE_ENV: development

volumes:
  createvid-postgres:
  createvid-rabbitmq:
  createvid-certs:
