#templates file needs to be defined before running application
$include: ./templates.js

logs:
  level: debug
  format: simple

server:
  app_endpoint: http://localhost:8080/
  port: 8000

database:
  user: createvid
  host: localhost
  database: createvid
  password: example
  port: 5432

#rabbitmq credentials
queue:
  url: amqp://localhost

auth:
  idSecret: "top secret1"
  accessSecret: "secret1"

mailing:
  sendgrid_key: 
    $env: SENDGRID_KEY

render:
  type: fakerender
  tasksDir:
    $resolvePath: ../temp

cdn:
  $env: CDN_URL

file_storage: gcloud_storage
gcloud_storage:
  project:
    $env: GC_PROJECT
  bucket:
    $env: GCS_BUCKET
  keyDir:
    $resolvePath: ../keys
  keyFilename:
    $env: KEY_FILE_FOR_GC  

render_temp_dir:
  $resolvePath: ../temp

templates_directory:
  $resolvePath: ../templates
