$include: ./common.yml

logs:
  sentry: 
    $env: SENTRY_URL
  level: debug
  format: simple

render:
  type: fakerender #nexrender
  tasksDir:
    $resolvePath: ../temp

queue:
  url: 
    $env: QUEUE_URL
  opts:
    cert:
      $resolvePath: ../keys/cert.pem
    key:
      $resolvePath: ../keys/key.pem
    passphrase:
    ca:
    - $resolvePath: ../keys/cacert.pem

auth:
  idSecret:
    $env: AUTH_ID_SECRET
  accessSecret:
    $env: AUTH_ACCESS_SECRET