$include: ./common.yml

logs:
  # sentry: 
  #   $env: SENTRY_URL
  level: debug
  format: simple

render:
  type: nexrender
  tasksDir:
    $resolvePath: ../temp

queue:
  url: 
    $env: QUEUE_URL
  opts:
    cert:
      $resolvePath: ../keys/cert.pem
    key:
      $resolvePath: ../keys/key.pem
    passphrase:
    ca:
    - $resolvePath: ../keys/cacert.pem
