export default {
	queue: {
		TASK_RENDER: 'tasks',
		TASK_INFO: 'info',
		TASK_STATUS: 'status',
    	WORKER_INFO: 'worker_info'
	},
	task: {
		status: {
			NEW: 'NEW',
			ERROR: 'ERROR',
			PREPARATION: 'PREPARATION',
			PREPARATION_ERROR: 'PREPARATION_ERROR',
			PREPARED: 'PREPARED',
			RENDER_PROCESS: 'RENDER_PROCESS',
			RENDER_SUCCESSFUL: 'RENDER_SUCCESSFUL',
			RENDER_ERROR: 'RENDER_ERROR',
			CLOUD_PROCESS: 'CLOUD_PROCESS',
			CLOUD_SUCCESSFUL: 'CLOUD_SUCCESSFUL',
			CLOUD_ERROR: 'CLOUD_ERROR',
			SUCCESSFUL: 'SUCCESSFUL',
		},
		messages: {
			UPDATE_TASK_STATUS: 'UPDATE_TASK_STATUS',
			ADD_URL: 'ADD_URL',
			ADD_NEW_TASK: 'ADD_NEW_TASK',
			ADD_ERROR: 'ADD_ERROR'
		}
	},
}
